"""
Asset Generator Module.
Creates project assets (README, CI/CD, scripts) and initializes Git.
"""
import os
import subprocess
from src.backend.llm_client import LLMClient

class AssetGenerator:
    def __init__(self):
        self.llm_client = LLMClient()

    def generate_assets(self, srs: dict, tech_stack: list) -> dict:
        """
        Generates README, CI/CD config, and setup scripts.
        """
        assets = {}
        
        # 1. README.md
        prompt = f"""
        Generate a professional README.md for the following project.
        Project: {srs.get('project_name')}
        Description: {srs.get('description')}
        Tech Stack: {tech_stack}
        
        Include sections: Introduction, Installation, Usage, and Testing.
        Return ONLY the markdown content.
        """
        try:
            readme_content = self.llm_client.generate_content(prompt)
            # Cleanup markdown block markers if present
            if readme_content.startswith("```markdown"):
                readme_content = readme_content.replace("```markdown", "").replace("```", "")
            assets["README.md"] = readme_content
        except Exception:
            assets["README.md"] = f"# {srs.get('project_name')}\n\nGenerated by SpecOps."

        # 2. CI/CD (GitHub Actions)
        assets[".github/workflows/python-app.yml"] = self._get_cicd_template()

        # 3. Setup Script (Windows)
        assets["setup.bat"] = self._get_setup_script()

        return assets

    def initialize_git(self, project_path: str):
        """
        Initializes a git repository and commits files.
        """
        try:
            # Check if git is installed
            subprocess.run(["git", "--version"], check=True, capture_output=True)
            
            # Init
            subprocess.run(["git", "init"], cwd=project_path, check=True, capture_output=True)
            
            # Add all
            subprocess.run(["git", "add", "."], cwd=project_path, check=True, capture_output=True)
            
            # Commit
            subprocess.run(["git", "commit", "-m", "Initial commit by SpecOps"], cwd=project_path, check=True, capture_output=True)
            
            return True
        except Exception as e:
            print(f"Git initialization failed: {e}")
            return False

    def _get_cicd_template(self):
        return """
name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint src || true
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
"""

    def _get_setup_script(self):
        return """
@echo off
echo Installing dependencies...
pip install -r requirements.txt
echo Running tests...
pytest
pause
"""
